/**
 * Převod názvu týmu (země) na ISO kód vlajky.
 * Podporuje české i anglické názvy; ignoruje diakritiku a velikost písmen.
 * Vrací null, pokud název není rozpoznaná země (pak se použijí iniciály).
 */

function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // odstraní diakritiku
    .toLowerCase()
    .trim();
}

// Klíče jsou už normalizované (bez diakritiky, malá písmena).
const MAP: Record<string, string> = {
  // Česko + sousedé
  cesko: "cz",
  "ceska republika": "cz",
  czechia: "cz",
  "czech republic": "cz",
  slovensko: "sk",
  slovakia: "sk",
  nemecko: "de",
  germany: "de",
  rakousko: "at",
  austria: "at",
  polsko: "pl",
  poland: "pl",

  // Británie a Irsko
  anglie: "gb-eng",
  england: "gb-eng",
  skotsko: "gb-sct",
  scotland: "gb-sct",
  wales: "gb-wls",
  "severni irsko": "gb-nir",
  "northern ireland": "gb-nir",
  irsko: "ie",
  ireland: "ie",

  // Západní / jižní Evropa
  spanelsko: "es",
  spain: "es",
  francie: "fr",
  france: "fr",
  italie: "it",
  italy: "it",
  portugalsko: "pt",
  portugal: "pt",
  nizozemsko: "nl",
  nizozemi: "nl",
  holandsko: "nl",
  netherlands: "nl",
  belgie: "be",
  belgium: "be",
  svycarsko: "ch",
  switzerland: "ch",
  lucembursko: "lu",
  luxembourg: "lu",

  // Severní Evropa
  dansko: "dk",
  denmark: "dk",
  norsko: "no",
  norway: "no",
  svedsko: "se",
  sweden: "se",
  finsko: "fi",
  finland: "fi",
  island: "is",
  iceland: "is",

  // Střední / východní Evropa a Balkán
  madarsko: "hu",
  hungary: "hu",
  chorvatsko: "hr",
  croatia: "hr",
  srbsko: "rs",
  serbia: "rs",
  slovinsko: "si",
  slovenia: "si",
  rumunsko: "ro",
  romania: "ro",
  bulharsko: "bg",
  bulgaria: "bg",
  ukrajina: "ua",
  ukraine: "ua",
  rusko: "ru",
  russia: "ru",
  albanie: "al",
  albania: "al",
  gruzie: "ge",
  georgia: "ge",
  recko: "gr",
  greece: "gr",
  turecko: "tr",
  turkey: "tr",
  turkiye: "tr",
  "bosna a hercegovina": "ba",
  bosna: "ba",
  bosnia: "ba",
  "severni makedonie": "mk",
  makedonie: "mk",
  "north macedonia": "mk",
  "cerna hora": "me",
  montenegro: "me",
  kosovo: "xk",
  moldavsko: "md",
  moldova: "md",
  belorusko: "by",
  belarus: "by",
  estonsko: "ee",
  lotyssko: "lv",
  litva: "lt",
  kypr: "cy",
  cyprus: "cy",

  // Amerika
  brazilie: "br",
  brazil: "br",
  argentina: "ar",
  usa: "us",
  "spojene staty": "us",
  "united states": "us",
  mexiko: "mx",
  mexico: "mx",
  kanada: "ca",
  canada: "ca",
  uruguay: "uy",
  kolumbie: "co",
  colombia: "co",
  chile: "cl",
  peru: "pe",
  ekvador: "ec",
  ecuador: "ec",

  // Afrika / Asie / Oceánie
  maroko: "ma",
  morocco: "ma",
  senegal: "sn",
  nigerie: "ng",
  nigeria: "ng",
  kamerun: "cm",
  cameroon: "cm",
  ghana: "gh",
  japonsko: "jp",
  japan: "jp",
  "jizni korea": "kr",
  korea: "kr",
  "south korea": "kr",
  australie: "au",
  australia: "au",
  katar: "qa",
  qatar: "qa",
  "saudska arabie": "sa",
  "saudi arabia": "sa",
  iran: "ir",
  izrael: "il",
  israel: "il",
  uzbekistan: "uz",
  irak: "iq",
  iraq: "iq",
  jordansko: "jo",
  jordan: "jo",
  "spojene arabske emiraty": "ae",
  sae: "ae",
  uae: "ae",
  oman: "om",
  cina: "cn",
  china: "cn",
  indonesie: "id",
  indonesia: "id",
  bahrajn: "bh",

  // Afrika (MS 2026)
  egypt: "eg",
  tunisko: "tn",
  tunisia: "tn",
  alzirsko: "dz",
  algeria: "dz",
  "pobrezi slonoviny": "ci",
  "ivory coast": "ci",
  mali: "ml",
  "jihoafricka republika": "za",
  jar: "za",
  "south africa": "za",
  kongo: "cd",
  "dr kongo": "cd",
  "demokraticka republika kongo": "cd",
  kapverdy: "cv",
  "cape verde": "cv",
  angola: "ao",
  "burkina faso": "bf",
  guinea: "gn",
  zambie: "zm",

  // CONCACAF (MS 2026)
  kostarika: "cr",
  "costa rica": "cr",
  panama: "pa",
  jamajka: "jm",
  jamaica: "jm",
  honduras: "hn",
  salvador: "sv",
  "el salvador": "sv",
  guatemala: "gt",
  curacao: "cw",
  haiti: "ht",
  "trinidad a tobago": "tt",
  "trinidad and tobago": "tt",

  // Jižní Amerika (MS 2026)
  paraguay: "py",
  bolivie: "bo",
  bolivia: "bo",
  venezuela: "ve",

  // Oceánie (MS 2026)
  "novy zeland": "nz",
  "new zealand": "nz",
};

export function countryCode(teamName: string): string | null {
  return MAP[normalize(teamName)] ?? null;
}
